### ISSUE TITLE
add commits to changelog

### ISSUE THREAD

**Issue by kylemac** [carrot/bash-hockey-puck#2]
i'd like to see this feature come back, along with a pruning via #1

**Comment by kylemac** [comment]
looks like it may actually be a bug: https://github.com/carrot/bash-hockey-puck/blob/master/bash-hockey-puck.sh#L36-L40

**Comment by BrandonRomano** [comment]
@kylemac - Okay so I'm actually using https://github.com/carrot/ash-slapshot now -- which does have the feature where it has commits..

As far as this library is concerned, it is deprecated and I am no longer supporting it (I should add a thing in the README for that).

I've just been removing the commits in the pruning stage to just say the date because I've gone too long before the last push and there was a ton of messages.

I'll leave them in for further commits!

**Comment by kylemac** [comment]
ah shit. i knew that -- i just picked the wrong repo

**Comment by BrandonRomano** [comment]
Well I'm glad you made this mistake reminded me to add a deprecated notice ;)
